### ISSUE TITLE
Unable to replace missing data

### ISSUE THREAD

**Issue by saurabhnitrr** [WillKoehrsen/machine-learning-project#1]
while running the following snippet of code given [here](https://github.com/WillKoehrsen/machine-learning-project-walkthrough/blob/master/Machine%20Learning%20Project%20Part%201.ipynb) :
```
# Replace all occurrences of Not Available with numpy not a number
data = data.replace({'Not Available': np.nan})

# Iterate through the columns
for col in list(data.columns):
    # Select columns that should be numeric
    if ('ft²' in col or 'kBtu' in col or 'Metric Tons CO2e' in col or 'kWh' in 
        col or 'therms' in col or 'gal' in col or 'Score' in col):
        # Convert the data type to float
        data[col] = data[col].astype(float)
```
Following error occurs:
```
TypeError: Type aliases cannot be used with isinstance().
```

**Comment by WillKoehrsen** [comment]
I am not able to replicate this error. What version of `pandas` and Python are you using?

**Comment by saurabhnitrr** [comment]
Python 3.5.2  and pandas v(0.23.0)

**Comment by WillKoehrsen** [comment]
I am using `Python == 3.6.4` and `pandas == 0.23.0` and have no issues. I would try searching for your issue online or editing the code until it works!
